# Generated by Django 5.0.7 on 2024-07-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="name",
            field=models.CharField(default="Unnamed Event", max_length=100),
        ),
        migrations.AlterField(
            model_name="event",
            name="day",
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="event",
            name="duration",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_hour",
            field=models.IntegerField(),
        ),
    ]
